"""baseline schema

Revision ID: 1e616292cc4e
Revises:
Create Date: 2026-07-09 22:41:53.177430

Migracion baseline: crea el esquema COMPLETO (las 19 tablas actuales de
Base.metadata, via `import models` en backend/models/__init__.py).

NOTA sobre como se genero (WO F0-03): no hay un MySQL real disponible en el
entorno donde se autoro esta migracion (sin docker, sin servidor MySQL
local), y esta PROHIBIDO correr Alembic contra la DB Aiven compartida de
dev/prod. El DDL de abajo se obtuvo diffeando Base.metadata contra una DB
SQLite vacia en memoria (motor sincrono stdlib, solo como "pizarra en
blanco" para que Alembic emita los `op.create_table(...)` explicitos) y
fue revisado a mano. Los tipos de columna usados en los modelos son
SQLAlchemy genericos (Integer, String, Float, DateTime, Text, Boolean) sin
dialecto especifico, por lo que el DDL es valido para MySQL. Lo que
NO se verifico en este WO es un `alembic upgrade head` real contra MySQL
-- queda pendiente de un entorno con MySQL disponible (dev/Infra).

Para PROD, donde el esquema ya existe (fue creado por `create_all` del
lifespan), esta migracion NO se corre con `upgrade` -- se aplica con
`alembic stamp head` (ver backend/README.md, seccion Migraciones).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e616292cc4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_area_m2', sa.Float(), nullable=True),
    sa.Column('covered_area_m2', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('parking_spots', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('price_per_m2', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos_count', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_active', 'market_listings', ['status', 'city', 'property_type'], unique=False)
    op.create_index('ix_listing_city_type', 'market_listings', ['city', 'property_type'], unique=False)
    op.create_index(op.f('ix_market_listings_captured_at'), 'market_listings', ['captured_at'], unique=False)
    op.create_index(op.f('ix_market_listings_city'), 'market_listings', ['city'], unique=False)
    op.create_index(op.f('ix_market_listings_condition'), 'market_listings', ['condition'], unique=False)
    op.create_index(op.f('ix_market_listings_external_id'), 'market_listings', ['external_id'], unique=False)
    op.create_index(op.f('ix_market_listings_latitude'), 'market_listings', ['latitude'], unique=False)
    op.create_index(op.f('ix_market_listings_longitude'), 'market_listings', ['longitude'], unique=False)
    op.create_index(op.f('ix_market_listings_neighborhood'), 'market_listings', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_market_listings_operation'), 'market_listings', ['operation'], unique=False)
    op.create_index(op.f('ix_market_listings_price_per_m2'), 'market_listings', ['price_per_m2'], unique=False)
    op.create_index(op.f('ix_market_listings_property_type'), 'market_listings', ['property_type'], unique=False)
    op.create_index(op.f('ix_market_listings_province'), 'market_listings', ['province'], unique=False)
    op.create_index(op.f('ix_market_listings_rooms'), 'market_listings', ['rooms'], unique=False)
    op.create_index(op.f('ix_market_listings_source'), 'market_listings', ['source'], unique=False)
    op.create_index(op.f('ix_market_listings_status'), 'market_listings', ['status'], unique=False)
    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('tasar_index', sa.Float(), nullable=True),
    sa.Column('median_price_per_m2', sa.Float(), nullable=True),
    sa.Column('yoy_change_pct', sa.Float(), nullable=True),
    sa.Column('mom_change_pct', sa.Float(), nullable=True),
    sa.Column('active_listings', sa.Integer(), nullable=True),
    sa.Column('avg_days_on_market', sa.Integer(), nullable=True),
    sa.Column('new_permits', sa.Integer(), nullable=True),
    sa.Column('top_zones', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('pages_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('period_year', 'period_month', 'region', name='uq_monthly_period_region')
    )
    op.create_index(op.f('ix_monthly_reports_region'), 'monthly_reports', ['region'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_app_setting_ws_key')
    )
    op.create_index(op.f('ix_app_settings_workspace_id'), 'app_settings', ['workspace_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('tax_id', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_created_at'), 'clients', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_workspace_id'), 'clients', ['workspace_id'], unique=False)
    op.create_table('external_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('property_type', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_area_m2', sa.Float(), nullable=True),
    sa.Column('covered_area_m2', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('price_per_m2', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'source_url', name='uq_external_workspace_url')
    )
    op.create_index(op.f('ix_external_listings_city'), 'external_listings', ['city'], unique=False)
    op.create_index(op.f('ix_external_listings_neighborhood'), 'external_listings', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_external_listings_property_type'), 'external_listings', ['property_type'], unique=False)
    op.create_index(op.f('ix_external_listings_province'), 'external_listings', ['province'], unique=False)
    op.create_index(op.f('ix_external_listings_scraped_at'), 'external_listings', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_external_listings_source'), 'external_listings', ['source'], unique=False)
    op.create_index(op.f('ix_external_listings_source_url'), 'external_listings', ['source_url'], unique=False)
    op.create_index(op.f('ix_external_listings_workspace_id'), 'external_listings', ['workspace_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('property_type', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price_per_m2', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_captured_at'), 'price_history', ['captured_at'], unique=False)
    op.create_index(op.f('ix_price_history_city'), 'price_history', ['city'], unique=False)
    op.create_index(op.f('ix_price_history_neighborhood'), 'price_history', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_price_history_province'), 'price_history', ['province'], unique=False)
    op.create_index(op.f('ix_price_history_workspace_id'), 'price_history', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('license_number', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.String(length=40), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_area_m2', sa.Float(), nullable=True),
    sa.Column('covered_area_m2', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parking_spots', sa.Integer(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_workspace_id'), 'properties', ['workspace_id'], unique=False)
    op.create_table('appraisals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('client_contact', sa.String(length=200), nullable=True),
    sa.Column('client_email', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('suggested_value_min', sa.Float(), nullable=True),
    sa.Column('suggested_value_max', sa.Float(), nullable=True),
    sa.Column('suggested_value_mode', sa.Float(), nullable=True),
    sa.Column('suggested_value_per_m2', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('cap_rate', sa.Float(), nullable=True),
    sa.Column('rental_estimate', sa.Float(), nullable=True),
    sa.Column('comparables_count', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('legal_remarks', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appraisals_assigned_to'), 'appraisals', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_appraisals_code'), 'appraisals', ['code'], unique=True)
    op.create_index(op.f('ix_appraisals_status'), 'appraisals', ['status'], unique=False)
    op.create_index(op.f('ix_appraisals_workspace_id'), 'appraisals', ['workspace_id'], unique=False)
    op.create_table('market_studies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('suggested_value_min', sa.Float(), nullable=True),
    sa.Column('suggested_value_max', sa.Float(), nullable=True),
    sa.Column('suggested_value_mode', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_studies_workspace_id'), 'market_studies', ['workspace_id'], unique=False)
    op.create_table('property_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=True),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_photos_property_id'), 'property_photos', ['property_id'], unique=False)
    op.create_table('appraisal_comparables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('market_listing_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('adjusted_price', sa.Float(), nullable=True),
    sa.Column('adjusted_price_per_m2', sa.Float(), nullable=True),
    sa.Column('adjustments_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.ForeignKeyConstraint(['market_listing_id'], ['market_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appraisal_comparables_appraisal_id'), 'appraisal_comparables', ['appraisal_id'], unique=False)
    op.create_index(op.f('ix_appraisal_comparables_market_listing_id'), 'appraisal_comparables', ['market_listing_id'], unique=False)
    op.create_table('appraisal_signatures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('signature_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appraisal_signatures_appraisal_id'), 'appraisal_signatures', ['appraisal_id'], unique=False)
    op.create_table('collaboration_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_study_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('anchor', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['market_study_id'], ['market_studies.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['collaboration_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_comments_market_study_id'), 'collaboration_comments', ['market_study_id'], unique=False)
    op.create_table('collaborations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_study_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('opinion_value', sa.Float(), nullable=True),
    sa.Column('opinion_note', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['market_study_id'], ['market_studies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborations_market_study_id'), 'collaborations', ['market_study_id'], unique=False)
    op.create_table('comparables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_study_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('source_property_id', sa.Integer(), nullable=True),
    sa.Column('external_listing_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_area_m2', sa.Float(), nullable=True),
    sa.Column('covered_area_m2', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('price_per_m2', sa.Float(), nullable=True),
    sa.Column('adjusted_price', sa.Float(), nullable=True),
    sa.Column('adjusted_price_per_m2', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['external_listing_id'], ['external_listings.id'], ),
    sa.ForeignKeyConstraint(['market_study_id'], ['market_studies.id'], ),
    sa.ForeignKeyConstraint(['source_property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparables_market_study_id'), 'comparables', ['market_study_id'], unique=False)
    op.create_table('inbox_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('sender_type', sa.String(length=40), nullable=True),
    sa.Column('sender_name', sa.String(length=200), nullable=True),
    sa.Column('sender_subtitle', sa.String(length=200), nullable=True),
    sa.Column('avatar_color', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=250), nullable=False),
    sa.Column('preview', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('related_appraisal_id', sa.Integer(), nullable=True),
    sa.Column('related_property_id', sa.Integer(), nullable=True),
    sa.Column('related_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_assigned_to_me', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['related_appraisal_id'], ['appraisals.id'], ),
    sa.ForeignKeyConstraint(['related_property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_messages_created_at'), 'inbox_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_inbox_messages_is_assigned_to_me'), 'inbox_messages', ['is_assigned_to_me'], unique=False)
    op.create_index(op.f('ix_inbox_messages_is_read'), 'inbox_messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_inbox_messages_kind'), 'inbox_messages', ['kind'], unique=False)
    op.create_index(op.f('ix_inbox_messages_related_appraisal_id'), 'inbox_messages', ['related_appraisal_id'], unique=False)
    op.create_index(op.f('ix_inbox_messages_user_id'), 'inbox_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_inbox_messages_workspace_id'), 'inbox_messages', ['workspace_id'], unique=False)
    op.create_table('adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comparable_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['comparable_id'], ['comparables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustments_comparable_id'), 'adjustments', ['comparable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjustments_comparable_id'), table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_index(op.f('ix_inbox_messages_workspace_id'), table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_user_id'), table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_related_appraisal_id'), table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_kind'), table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_is_read'), table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_is_assigned_to_me'), table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_created_at'), table_name='inbox_messages')
    op.drop_table('inbox_messages')
    op.drop_index(op.f('ix_comparables_market_study_id'), table_name='comparables')
    op.drop_table('comparables')
    op.drop_index(op.f('ix_collaborations_market_study_id'), table_name='collaborations')
    op.drop_table('collaborations')
    op.drop_index(op.f('ix_collaboration_comments_market_study_id'), table_name='collaboration_comments')
    op.drop_table('collaboration_comments')
    op.drop_index(op.f('ix_appraisal_signatures_appraisal_id'), table_name='appraisal_signatures')
    op.drop_table('appraisal_signatures')
    op.drop_index(op.f('ix_appraisal_comparables_market_listing_id'), table_name='appraisal_comparables')
    op.drop_index(op.f('ix_appraisal_comparables_appraisal_id'), table_name='appraisal_comparables')
    op.drop_table('appraisal_comparables')
    op.drop_index(op.f('ix_property_photos_property_id'), table_name='property_photos')
    op.drop_table('property_photos')
    op.drop_index(op.f('ix_market_studies_workspace_id'), table_name='market_studies')
    op.drop_table('market_studies')
    op.drop_index(op.f('ix_appraisals_workspace_id'), table_name='appraisals')
    op.drop_index(op.f('ix_appraisals_status'), table_name='appraisals')
    op.drop_index(op.f('ix_appraisals_code'), table_name='appraisals')
    op.drop_index(op.f('ix_appraisals_assigned_to'), table_name='appraisals')
    op.drop_table('appraisals')
    op.drop_index(op.f('ix_properties_workspace_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_price_history_workspace_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_province'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_neighborhood'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_city'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_captured_at'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_external_listings_workspace_id'), table_name='external_listings')
    op.drop_index(op.f('ix_external_listings_source_url'), table_name='external_listings')
    op.drop_index(op.f('ix_external_listings_source'), table_name='external_listings')
    op.drop_index(op.f('ix_external_listings_scraped_at'), table_name='external_listings')
    op.drop_index(op.f('ix_external_listings_province'), table_name='external_listings')
    op.drop_index(op.f('ix_external_listings_property_type'), table_name='external_listings')
    op.drop_index(op.f('ix_external_listings_neighborhood'), table_name='external_listings')
    op.drop_index(op.f('ix_external_listings_city'), table_name='external_listings')
    op.drop_table('external_listings')
    op.drop_index(op.f('ix_clients_workspace_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_created_at'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_app_settings_workspace_id'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_monthly_reports_region'), table_name='monthly_reports')
    op.drop_table('monthly_reports')
    op.drop_index(op.f('ix_market_listings_status'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_source'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_rooms'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_province'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_property_type'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_price_per_m2'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_operation'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_neighborhood'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_longitude'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_latitude'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_external_id'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_condition'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_city'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_captured_at'), table_name='market_listings')
    op.drop_index('ix_listing_city_type', table_name='market_listings')
    op.drop_index('ix_listing_active', table_name='market_listings')
    op.drop_table('market_listings')
    # ### end Alembic commands ###
