"""sync_prod_missing_cols

Revision ID: 32456ebf3597
Revises: f7a8b9c0d1e2
Create Date: 2026-07-10 19:57:23.986205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32456ebf3597'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_index(op.f('ix_invitations_workspace_id'), 'invitations', ['workspace_id'], unique=False)
    op.drop_index('ix_apcomp_appraisal', table_name='appraisal_comparables')
    op.drop_index('ix_apcomp_listing', table_name='appraisal_comparables')
    op.create_index(op.f('ix_appraisal_comparables_appraisal_id'), 'appraisal_comparables', ['appraisal_id'], unique=False)
    op.create_index(op.f('ix_appraisal_comparables_market_listing_id'), 'appraisal_comparables', ['market_listing_id'], unique=False)
    op.create_foreign_key(None, 'appraisal_comparables', 'appraisals', ['appraisal_id'], ['id'])
    op.create_foreign_key(None, 'appraisal_comparables', 'market_listings', ['market_listing_id'], ['id'])
    op.drop_index('code', table_name='appraisals')
    op.create_index(op.f('ix_appraisals_assigned_to'), 'appraisals', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_appraisals_code'), 'appraisals', ['code'], unique=True)
    op.create_index(op.f('ix_appraisals_status'), 'appraisals', ['status'], unique=False)
    op.drop_constraint('appraisals_ibfk_3', 'appraisals', type_='foreignkey')
    op.create_foreign_key(None, 'appraisals', 'users', ['assigned_to'], ['id'])
    op.drop_column('appraisals', 'market_study_id')
    op.create_foreign_key(None, 'comparables', 'external_listings', ['external_listing_id'], ['id'])
    op.create_foreign_key(None, 'comparables', 'properties', ['source_property_id'], ['id'])
    op.add_column('properties', sa.Column('is_demo', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_properties_is_demo'), 'properties', ['is_demo'], unique=False)
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_is_demo'), 'users', ['is_demo'], unique=False)
    op.add_column('wa_conversations', sa.Column('is_demo', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_wa_conversations_is_demo'), 'wa_conversations', ['is_demo'], unique=False)
    op.drop_index('uq_workspace_bot_config_meta_phone_number_id', table_name='workspace_bot_config')
    op.drop_index('uq_workspace_bot_config_workspace', table_name='workspace_bot_config')
    op.drop_index('ix_workspace_bot_config_meta_phone_number_id', table_name='workspace_bot_config')
    op.create_index(op.f('ix_workspace_bot_config_meta_phone_number_id'), 'workspace_bot_config', ['meta_phone_number_id'], unique=True)
    op.drop_index('ix_workspace_bot_config_workspace_id', table_name='workspace_bot_config')
    op.create_index(op.f('ix_workspace_bot_config_workspace_id'), 'workspace_bot_config', ['workspace_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_bot_config_workspace_id'), table_name='workspace_bot_config')
    op.create_index('ix_workspace_bot_config_workspace_id', 'workspace_bot_config', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_workspace_bot_config_meta_phone_number_id'), table_name='workspace_bot_config')
    op.create_index('ix_workspace_bot_config_meta_phone_number_id', 'workspace_bot_config', ['meta_phone_number_id'], unique=False)
    op.create_index('uq_workspace_bot_config_workspace', 'workspace_bot_config', ['workspace_id'], unique=False)
    op.create_index('uq_workspace_bot_config_meta_phone_number_id', 'workspace_bot_config', ['meta_phone_number_id'], unique=False)
    op.drop_index(op.f('ix_wa_conversations_is_demo'), table_name='wa_conversations')
    op.drop_column('wa_conversations', 'is_demo')
    op.drop_index(op.f('ix_users_is_demo'), table_name='users')
    op.drop_column('users', 'is_demo')
    op.drop_index(op.f('ix_properties_is_demo'), table_name='properties')
    op.drop_column('properties', 'is_demo')
    op.drop_constraint(None, 'comparables', type_='foreignkey')
    op.drop_constraint(None, 'comparables', type_='foreignkey')
    op.add_column('appraisals', sa.Column('market_study_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appraisals', type_='foreignkey')
    op.create_foreign_key('appraisals_ibfk_3', 'appraisals', 'market_studies', ['market_study_id'], ['id'])
    op.drop_index(op.f('ix_appraisals_status'), table_name='appraisals')
    op.drop_index(op.f('ix_appraisals_code'), table_name='appraisals')
    op.drop_index(op.f('ix_appraisals_assigned_to'), table_name='appraisals')
    op.create_index('code', 'appraisals', ['code'], unique=False)
    op.drop_constraint(None, 'appraisal_comparables', type_='foreignkey')
    op.drop_constraint(None, 'appraisal_comparables', type_='foreignkey')
    op.drop_index(op.f('ix_appraisal_comparables_market_listing_id'), table_name='appraisal_comparables')
    op.drop_index(op.f('ix_appraisal_comparables_appraisal_id'), table_name='appraisal_comparables')
    op.create_index('ix_apcomp_listing', 'appraisal_comparables', ['market_listing_id'], unique=False)
    op.create_index('ix_apcomp_appraisal', 'appraisal_comparables', ['appraisal_id'], unique=False)
    op.drop_index(op.f('ix_invitations_workspace_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
