plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\Code\\ACM\\landing"
publishOrigin = "default"
base = "D:\\Code\\ACM\\landing"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]